# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # encoders:
    #     Symfony\Component\Security\Core\User\User:
    #         algorithm: bcrypt
    #         cost: 12
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        custom_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
    #         pattern: ^/(?!login)
    #         # http_basic: ~
    #         form_login:
    #             login_path: login_form
    #             check_path: login_check
    #             provider: custom_provider

    #         #provider: custom_provider
    #         # guard:
    #         #     authenticators:
    #         #         - app.token_authenticator
    #         # activate different ways to authenticate

    #         # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #         #http_basic: ~

    #         # https://symfony.com/doc/current/security/form_login_setup.html
    #         #form_login: ~
    # access_control:
    #     - { path: ^/login$,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
